package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbFacturacionId generated by hbm2java
 */
public class AltbFacturacionId  implements java.io.Serializable {


     private String idFact;
     private String idReserva;

    public AltbFacturacionId() {
    }

    public AltbFacturacionId(String idFact, String idReserva) {
       this.idFact = idFact;
       this.idReserva = idReserva;
    }
   
    public String getIdFact() {
        return this.idFact;
    }
    
    public void setIdFact(String idFact) {
        this.idFact = idFact;
    }
    public String getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(String idReserva) {
        this.idReserva = idReserva;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AltbFacturacionId) ) return false;
		 AltbFacturacionId castOther = ( AltbFacturacionId ) other; 
         
		 return ( (this.getIdFact()==castOther.getIdFact()) || ( this.getIdFact()!=null && castOther.getIdFact()!=null && this.getIdFact().equals(castOther.getIdFact()) ) )
 && ( (this.getIdReserva()==castOther.getIdReserva()) || ( this.getIdReserva()!=null && castOther.getIdReserva()!=null && this.getIdReserva().equals(castOther.getIdReserva()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdFact() == null ? 0 : this.getIdFact().hashCode() );
         result = 37 * result + ( getIdReserva() == null ? 0 : this.getIdReserva().hashCode() );
         return result;
   }   


}


