package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbMesasAreaId generated by hbm2java
 */
public class AltbMesasAreaId  implements java.io.Serializable {


     private String idArea;
     private String idMesa;

    public AltbMesasAreaId() {
    }

    public AltbMesasAreaId(String idArea, String idMesa) {
       this.idArea = idArea;
       this.idMesa = idMesa;
    }
   
    public String getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(String idArea) {
        this.idArea = idArea;
    }
    public String getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(String idMesa) {
        this.idMesa = idMesa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AltbMesasAreaId) ) return false;
		 AltbMesasAreaId castOther = ( AltbMesasAreaId ) other; 
         
		 return ( (this.getIdArea()==castOther.getIdArea()) || ( this.getIdArea()!=null && castOther.getIdArea()!=null && this.getIdArea().equals(castOther.getIdArea()) ) )
 && ( (this.getIdMesa()==castOther.getIdMesa()) || ( this.getIdMesa()!=null && castOther.getIdMesa()!=null && this.getIdMesa().equals(castOther.getIdMesa()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdArea() == null ? 0 : this.getIdArea().hashCode() );
         result = 37 * result + ( getIdMesa() == null ? 0 : this.getIdMesa().hashCode() );
         return result;
   }   


}


