package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbReservaClientesId generated by hbm2java
 */
public class AltbReservaClientesId  implements java.io.Serializable {


     private String idReserva;
     private String idCliente;

    public AltbReservaClientesId() {
    }

    public AltbReservaClientesId(String idReserva, String idCliente) {
       this.idReserva = idReserva;
       this.idCliente = idCliente;
    }
   
    public String getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(String idReserva) {
        this.idReserva = idReserva;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AltbReservaClientesId) ) return false;
		 AltbReservaClientesId castOther = ( AltbReservaClientesId ) other; 
         
		 return ( (this.getIdReserva()==castOther.getIdReserva()) || ( this.getIdReserva()!=null && castOther.getIdReserva()!=null && this.getIdReserva().equals(castOther.getIdReserva()) ) )
 && ( (this.getIdCliente()==castOther.getIdCliente()) || ( this.getIdCliente()!=null && castOther.getIdCliente()!=null && this.getIdCliente().equals(castOther.getIdCliente()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdReserva() == null ? 0 : this.getIdReserva().hashCode() );
         result = 37 * result + ( getIdCliente() == null ? 0 : this.getIdCliente().hashCode() );
         return result;
   }   


}


