package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbArea generated by hbm2java
 */
public class AltbArea  implements java.io.Serializable {


     private String idArea;
     private String descArea;
     private String linkImg;

    public AltbArea() {
    }

    public AltbArea(String idArea, String descArea, String linkImg) {
       this.idArea = idArea;
       this.descArea = descArea;
       this.linkImg = linkImg;
    }
   
    public String getIdArea() {
        return this.idArea;
    }
    
    public void setIdArea(String idArea) {
        this.idArea = idArea;
    }
    public String getDescArea() {
        return this.descArea;
    }
    
    public void setDescArea(String descArea) {
        this.descArea = descArea;
    }
    public String getLinkImg() {
        return this.linkImg;
    }
    
    public void setLinkImg(String linkImg) {
        this.linkImg = linkImg;
    }




}


