package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbMesasArea generated by hbm2java
 */
public class AltbMesasArea  implements java.io.Serializable {


     private AltbMesasAreaId id;

    public AltbMesasArea() {
    }

    public AltbMesasArea(AltbMesasAreaId id) {
       this.id = id;
    }
   
    public AltbMesasAreaId getId() {
        return this.id;
    }
    
    public void setId(AltbMesasAreaId id) {
        this.id = id;
    }




}


