package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AltbReservaClientes generated by hbm2java
 */
public class AltbReservaClientes  implements java.io.Serializable {


     private AltbReservaClientesId id;
     private String estadoFact;
     private Date fhCarga;

    public AltbReservaClientes() {
    }

    public AltbReservaClientes(AltbReservaClientesId id, String estadoFact, Date fhCarga) {
       this.id = id;
       this.estadoFact = estadoFact;
       this.fhCarga = fhCarga;
    }
   
    public AltbReservaClientesId getId() {
        return this.id;
    }
    
    public void setId(AltbReservaClientesId id) {
        this.id = id;
    }
    public String getEstadoFact() {
        return this.estadoFact;
    }
    
    public void setEstadoFact(String estadoFact) {
        this.estadoFact = estadoFact;
    }
    public Date getFhCarga() {
        return this.fhCarga;
    }
    
    public void setFhCarga(Date fhCarga) {
        this.fhCarga = fhCarga;
    }




}


