package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbMesas generated by hbm2java
 */
public class AltbMesas  implements java.io.Serializable {


     private String idMesa;
     private String descMesa;
     private String linkImg;

    public AltbMesas() {
    }

    public AltbMesas(String idMesa, String descMesa, String linkImg) {
       this.idMesa = idMesa;
       this.descMesa = descMesa;
       this.linkImg = linkImg;
    }
   
    public String getIdMesa() {
        return this.idMesa;
    }
    
    public void setIdMesa(String idMesa) {
        this.idMesa = idMesa;
    }
    public String getDescMesa() {
        return this.descMesa;
    }
    
    public void setDescMesa(String descMesa) {
        this.descMesa = descMesa;
    }
    public String getLinkImg() {
        return this.linkImg;
    }
    
    public void setLinkImg(String linkImg) {
        this.linkImg = linkImg;
    }




}


