package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * AltbFacturacion generated by hbm2java
 */
public class AltbFacturacion  implements java.io.Serializable {


     private AltbFacturacionId id;
     private Float totalFact;
     private Date fhCarga;

    public AltbFacturacion() {
    }

	
    public AltbFacturacion(AltbFacturacionId id, Date fhCarga) {
        this.id = id;
        this.fhCarga = fhCarga;
    }
    public AltbFacturacion(AltbFacturacionId id, Float totalFact, Date fhCarga) {
       this.id = id;
       this.totalFact = totalFact;
       this.fhCarga = fhCarga;
    }
   
    public AltbFacturacionId getId() {
        return this.id;
    }
    
    public void setId(AltbFacturacionId id) {
        this.id = id;
    }
    public Float getTotalFact() {
        return this.totalFact;
    }
    
    public void setTotalFact(Float totalFact) {
        this.totalFact = totalFact;
    }
    public Date getFhCarga() {
        return this.fhCarga;
    }
    
    public void setFhCarga(Date fhCarga) {
        this.fhCarga = fhCarga;
    }




}


