package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbHsy generated by hbm2java
 */
public class AltbHsy  implements java.io.Serializable {


     private String iu4789;
     private String uu7879;
     private String cu5479;

    public AltbHsy() {
    }

    public AltbHsy(String iu4789, String uu7879, String cu5479) {
       this.iu4789 = iu4789;
       this.uu7879 = uu7879;
       this.cu5479 = cu5479;
    }
   
    public String getIu4789() {
        return this.iu4789;
    }
    
    public void setIu4789(String iu4789) {
        this.iu4789 = iu4789;
    }
    public String getUu7879() {
        return this.uu7879;
    }
    
    public void setUu7879(String uu7879) {
        this.uu7879 = uu7879;
    }
    public String getCu5479() {
        return this.cu5479;
    }
    
    public void setCu5479(String cu5479) {
        this.cu5479 = cu5479;
    }




}


