package objects;
// Generated Sep 25, 2014 11:43:14 PM by Hibernate Tools 4.3.1



/**
 * AltbPaquete generated by hbm2java
 */
public class AltbPaquete  implements java.io.Serializable {


     private String idPaquete;
     private String desPaquete;
     private String cmPaquete;
     private String linkImg;
     private Float precio;

    public AltbPaquete() {
    }

	
    public AltbPaquete(String idPaquete, String desPaquete, String cmPaquete, String linkImg) {
        this.idPaquete = idPaquete;
        this.desPaquete = desPaquete;
        this.cmPaquete = cmPaquete;
        this.linkImg = linkImg;
    }
    public AltbPaquete(String idPaquete, String desPaquete, String cmPaquete, String linkImg, Float precio) {
       this.idPaquete = idPaquete;
       this.desPaquete = desPaquete;
       this.cmPaquete = cmPaquete;
       this.linkImg = linkImg;
       this.precio = precio;
    }
   
    public String getIdPaquete() {
        return this.idPaquete;
    }
    
    public void setIdPaquete(String idPaquete) {
        this.idPaquete = idPaquete;
    }
    public String getDesPaquete() {
        return this.desPaquete;
    }
    
    public void setDesPaquete(String desPaquete) {
        this.desPaquete = desPaquete;
    }
    public String getCmPaquete() {
        return this.cmPaquete;
    }
    
    public void setCmPaquete(String cmPaquete) {
        this.cmPaquete = cmPaquete;
    }
    public String getLinkImg() {
        return this.linkImg;
    }
    
    public void setLinkImg(String linkImg) {
        this.linkImg = linkImg;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


