-- MySQL Script generated by MySQL Workbench
-- 10/27/14 11:09:22
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;
-- -----------------------------------------------------
-- Schema altabar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `altabar` ;
CREATE SCHEMA IF NOT EXISTS `altabar` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `altabar` ;

-- -----------------------------------------------------
-- Table `altabar`.`altb_mesas_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_mesas_area` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_mesas_area` (
  `ID_MESA` VARCHAR(50) NOT NULL,
  `ID_AREA` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`ID_AREA`, `ID_MESA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_MESA_AREA` ON `altabar`.`altb_mesas_area` (`ID_AREA` ASC, `ID_MESA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_area` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_area` (
  `ID_AREA` VARCHAR(50) NOT NULL,
  `DESC_AREA` VARCHAR(500) NOT NULL,
  `LINK_IMG` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`ID_AREA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_AREA` ON `altabar`.`altb_area` (`ID_AREA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_clientes` (
  `ID_CLIENTE` VARCHAR(50) NOT NULL,
  `NOMBRE` VARCHAR(75) NOT NULL,
  `APELLIDO` VARCHAR(75) NOT NULL,
  `E_MAIL` VARCHAR(50) NOT NULL,
  `CELULAR` VARCHAR(8) NOT NULL,
  `SEXO` VARCHAR(1) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `FH_REGISTRO` DATE NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_CLIENTES` ON `altabar`.`altb_clientes` (`ID_CLIENTE` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_facturacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_facturacion` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_facturacion` (
  `ID_FACT` VARCHAR(50) NOT NULL,
  `ID_RESERVA` VARCHAR(50) NOT NULL,
  `TOTAL_FACT` FLOAT NULL DEFAULT NULL,
  `FH_CARGA` DATE NOT NULL,
  PRIMARY KEY (`ID_FACT`, `ID_RESERVA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_FATURACION` ON `altabar`.`altb_facturacion` (`ID_FACT` ASC, `ID_RESERVA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_hsy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_hsy` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_hsy` (
  `IU4789` VARCHAR(200) NOT NULL,
  `UU7879` VARCHAR(500) NOT NULL,
  `CU5479` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`IU4789`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_HSY` ON `altabar`.`altb_hsy` (`IU4789` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_mesas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_mesas` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_mesas` (
  `ID_MESA` VARCHAR(50) NOT NULL,
  `DESC_MESA` VARCHAR(500) NOT NULL,
  `LINK_IMG` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`ID_MESA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_MESAS` ON `altabar`.`altb_mesas` (`ID_MESA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_paquete` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_paquete` (
  `ID_PAQUETE` VARCHAR(50) NOT NULL,
  `DES_PAQUETE` VARCHAR(500) NOT NULL,
  `CM_PAQUETE` VARCHAR(2000) NOT NULL,
  `LINK_IMG` VARCHAR(2000) NOT NULL,
  `PRECIO` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`ID_PAQUETE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_PAQUETE` ON `altabar`.`altb_paquete` (`ID_PAQUETE` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_reserva_clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_reserva_clientes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_reserva_clientes` (
  `ID_RESERVA` VARCHAR(50) NOT NULL,
  `ESTADO_FACT` VARCHAR(1) NOT NULL,
  `FH_CARGA` DATE NOT NULL,
  PRIMARY KEY (`ID_RESERVA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_RESERVA_CLIENTES` ON `altabar`.`altb_reserva_clientes` (`ID_RESERVA` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `altabar`.`altb_reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `altabar`.`altb_reserva` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `altabar`.`altb_reserva` (
  `ID_RESERVA` VARCHAR(50) NOT NULL,
  `ID_CLIENTE` VARCHAR(50) NOT NULL,
  `ID_PAQUETE` VARCHAR(50) NOT NULL,
  `ID_MESA` VARCHAR(50) NOT NULL,
  `DE_RESERVA` VARCHAR(500) NOT NULL,
  `CM_RESERVA` VARCHAR(2000) NOT NULL,
  `FH_CARGA` DATE NOT NULL,
  PRIMARY KEY (`ID_RESERVA`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE UNIQUE INDEX `PK_ALTB_RESERVA` ON `altabar`.`altb_reserva` (`ID_RESERVA` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
