// mesas
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M001','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M002','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M003','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M004','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M005','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M006','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M007','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M008','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M009','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M010','Mesa para restaurante',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M011','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M012','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M013','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M014','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M015','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M016','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M017','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M018','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M019','Mesa para club',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M020','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M021','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M022','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M023','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M024','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M025','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M026','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M027','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M028','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M029','Mesa para terraza',  '   ');
INSERT INTO `altabar`.`altb_mesas` (`ID_MESA`, `DESC_MESA`, `LINK_IMG`) VALUE('M030','Mesa para terraza',  '   ');


// mesas areas
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M001','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M002','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M003','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M004','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M005','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M006','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M007','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M008','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M009','ALTB_RESTAURANTE'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M010','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M011','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M012','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M013','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M014','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M015','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M016','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M017','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M018','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M019','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M020','ALTB_CLUB'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M021','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M022','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M023','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M024','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M025','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M026','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M027','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M028','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M029','ALTB_TERRAZA'  );
INSERT INTO `altabar`.`altb_mesas_area` (`ID_MESA`, `ID_AREA`) VALUE('M030','ALTB_TERRAZA'  );
